version: "3"

networks:
  laravel:

volumes:
  db-volume:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_cloud
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: db_cloud
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - laravel

  app:
    container_name: app_cloud
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
      DB_HOST: db_cloud
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-homestead}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - laravel

